domecode/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from . import devsettings
from django.conf.urls.static import static
from decouple import config

admin.autodiscover()

urlpatterns = [
    path(config("ADMIN_URL"), admin.site.urls),
    path("oauth/", include("social_django.urls", namespace="social")),
    path(
        "profile/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("users.urls")),
    path("", include("notes.urls")),
    path("", include("forum.urls")),
    path("todo/", include("todo.urls")),
    path("tracks/", include("resources.urls")),
    path("practice/", include("coder.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("quiz/", include("quizzes.urls")),
    path("products/", include("creator.urls")),
    path("fusion/", include("fusion.urls")),
    # REST FRAMEWORK URLS
    path("api/todo/", include("todo.api.urls", "todo_api")),
    path("api/notes/", include("notes.api.urls", "notes_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

elif devsettings.DEBUG:
    urlpatterns += static(devsettings.MEDIA_URL,
                          document_root=devsettings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=devsettings.STATIC_ROOT)

forum/urls.py
from django.urls import path
from . import views
from .views import (
    QueryCreateView,
    QueryListView,
    QueryUpdateView,
    QueryDeleteView,
    QueryDetailView,
    QueryLikeAPIToggle,
    QueryLikeToggle,
    AnswerCreateView,
    AnswerDeleteView,
    AnswerUpdateView,
    AnswerDetailView,
    AcceptAnswerView,
    CommentCreateView,
    CommentDeleteView,
    CommentUpdateView,
)

app_name = "forum"

urlpatterns = [
    # forum url
    path("forum/", QueryListView.as_view(), name="list"),
    path("forum/guidelines", views.guidelines, name="guidelines"),
    # query urls
    path("forum/query/new/", QueryCreateView.as_view(), name="query-create"),
    path("forum/query/<slug:slug>/", QueryDetailView.as_view(), name="detail"),
    path(
        "forum/query/<slug:slug>/update/",
        QueryUpdateView.as_view(),
        name="query-update",
    ),
    path(
        "forum/query/<slug:slug>/delete/",
        QueryDeleteView.as_view(),
        name="query-delete",
    ),
    path(
        "forum/query/<slug:slug>/like/",
        QueryLikeToggle.as_view(),
        name="query-likes-toggle",
    ),
    path(
        "api/forum/query/<slug:slug>/like/",
        QueryLikeAPIToggle.as_view(),
        name="query-likes-api-toggle",
    ),
    # answer urls
    path(
        "forum/query/<slug:qslug>/answer/create/",
        AnswerCreateView.as_view(),
        name="answer-create",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:slug>/",
        AnswerDetailView.as_view(),
        name="answer-detail",
    ),
    path(
        "forum/query/<slug:qslug>/answer/update/<slug:slug>",
        AnswerUpdateView.as_view(),
        name="answer-update",
    ),
    path(
        "forum/query/<slug:qslug>/answer/delete/<slug:slug>/",
        AnswerDeleteView.as_view(),
        name="answer-delete",
    ),
    path(
        "forum/query/<slug:qslug>/answer/accept/<slug:slug>/",
        AcceptAnswerView.as_view(),
        name="accept",
    ),
    # commenturls
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/create/",
        CommentCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/update/<slug:slug>",
        CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/delete/<slug:slug>/",
        CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    # path('forum/query/<slug:qslug>/answer/like/',
    #     AnswerLikeToggle.as_view(), name='answer-likes-toggle'),
    #  path('api/forum/answer/<slug:slug>/like/',
    #      AnswerLikeAPIToggle.as_view(), name='answer-likes-api-toggle'),
]

todo/urls.py
from django.urls import path
from .views import TodoCreateView, TodoListView, TodoUpdateView, TodoDeleteView

app_name = "todo"

urlpatterns = [
    path("", TodoListView.as_view(), name="list"),
    path("<int:pk>/", TodoUpdateView.as_view(), name="update"),
    path("new/", TodoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.urls import path
from . import views
from users.views import AccountDetailView, Leaderboard

app_name = "users"

urlpatterns = [
    path("leaderboard/", Leaderboard.as_view(), name="leaderboard"),
    path("profile/register/", views.signup, name="register"),
    path("profile/edit/", views.profile, name="profile"),
    path("user/<slug:slug>/", AccountDetailView.as_view(), name="profilepage"),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.urls import reverse
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.utils.crypto import get_random_string


class Query(models.Model):
    CATEGORY = [
        ("General Development", "General Development"),
        ("Web Development", "Web Development"),
        ("CS", "Computer Science"),
        ("About DomeCode", "About DomeCode"),
    ]

    title = models.CharField(max_length=240)
    user = models.ForeignKey(get_user_model(),
                             null=True,
                             on_delete=models.SET_NULL)
    content = RichTextField(null=True, blank=True)
    likes = models.ManyToManyField(User,
                                   default=None,
                                   blank=True,
                                   related_name="query_likes")
    category = models.CharField(max_length=30, choices=CATEGORY, default="GEN")
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, unique=True, max_length=256)

    def __str__(self):
        return self.title

    def likes_as_flat_user_id_list(self):
        return self.likes.values_list("id", flat=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("forum:detail", kwargs={"slug": self.slug})


class Answer(models.Model):
    user = models.ForeignKey(get_user_model(),
                             null=True,
                             on_delete=models.SET_NULL)
    query = models.ForeignKey(Query, on_delete=models.CASCADE)
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User,
                                   default=None,
                                   blank=True,
                                   related_name="answer_likes")
    slug = models.SlugField(null=True, unique=True, max_length=256)
    isaccepted = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        uniqueid = get_random_string(length=8)
        self.slug = slugify(uniqueid)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("forum:detail", kwargs={"slug": self.query.slug})


class Comment(models.Model):
    user = models.ForeignKey(get_user_model(),
                             null=True,
                             on_delete=models.SET_NULL)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, unique=False, max_length=256)

    def get_absolute_url(self):
        return reverse("forum:detail", kwargs={"slug": self.answer.query.slug})

    def save(self, *args, **kwargs):
        uniqueid = get_random_string(length=8)
        self.slug = slugify(uniqueid)
        super().save(*args, **kwargs)

forum/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from .models import Query, Answer, Comment
from django.db.models import Q
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from domecode.mixins import PageTitleMixin


def guidelines(request):
    return render(request, "forum/guidelines.html",
                  {"title": "Forum Guidelines"})


class QueryListView(PageTitleMixin, generic.ListView):
    model = Query
    template_name = "forum/query_list.html"
    paginate_by = 15
    context_object_name = "query"
    ordering = ["-last_modified"]
    title = "Forum"

    def get_queryset(self, *args, **kwargs):
        object_list = super(QueryListView, self).get_queryset(*args, **kwargs)
        search = self.request.GET.get("q", None)
        if search:
            object_list = object_list.filter(
                Q(title__contains=search)
                | Q(content__contains=search)
                | Q(category__contains=search)).order_by("-last_modified")
            return object_list
        else:
            return object_list


class QueryDetailView(PageTitleMixin, generic.DetailView):
    model = Query
    template_name = "forum/query_detail.html"
    title = "Forum"


class QueryCreateView(PageTitleMixin, LoginRequiredMixin, generic.CreateView):
    model = Query
    template_name = "forum/query_form.html"
    fields = ["title", "content", "category"]
    title = "Ask"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class QueryUpdateView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                      generic.UpdateView):
    model = Query
    fields = ["title", "content", "category"]
    title = "Edit Query"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        query = self.get_object()
        if self.request.user == query.user:
            return True


class QueryDeleteView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                      generic.DeleteView):
    model = Query
    success_url = reverse_lazy("forum:list")
    title = "Delete Query"

    def test_func(self):
        query = self.get_object()
        if self.request.user == query.user:
            return True


class AnswerCreateView(LoginRequiredMixin, PageTitleMixin, generic.CreateView):
    model = Answer
    template_name = "forum/answer_form.html"
    fields = ["content"]
    title = "Answer"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.query = Query.objects.get(slug=self.kwargs["qslug"])
        return super().form_valid(form)


class AnswerUpdateView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                       generic.UpdateView):
    model = Answer
    template_name = "forum/answer_form.html"
    fields = ["content"]
    title = "Edit Answer"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        answer = self.get_object()
        if self.request.user == answer.user:
            return True


class AnswerDeleteView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                       generic.DeleteView):
    model = Answer
    success_url = reverse_lazy("forum:list")
    title = "Delete Answer"

    def test_func(self):
        answer = self.get_object()
        if self.request.user == answer.user:
            return True


class AcceptAnswerView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                       generic.UpdateView):
    model = Answer
    fields = ["isaccepted"]
    template_name = "forum/answer_accept.html"
    title = "Accept Answer"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        answer = self.get_object()
        if self.request.user == answer.query.user:
            return True


class AnswerDetailView(PageTitleMixin, generic.DetailView):
    model = Answer
    template_name = "forum/answer_detail.html"
    title = "Answer"


class CommentCreateView(LoginRequiredMixin, PageTitleMixin,
                        generic.CreateView):
    model = Comment
    template_name = "forum/comment_form.html"
    fields = ["content"]
    title = "Comment"

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.answer = Answer.objects.get(slug=self.kwargs["aslug"])
        return super().form_valid(form)


class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin,
                        PageTitleMixin, generic.UpdateView):
    model = Comment
    template_name = "forum/comment_form.html"
    fields = ["content"]
    title = "Edit Comment"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user:
            return True


class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin,
                        PageTitleMixin, generic.DeleteView):
    model = Comment
    success_url = reverse_lazy("forum:list")
    title = "Delete Comment"

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.user:
            return True


class QueryLikeToggle(generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        # query = get_object_or_404(Query, slug=self.kwargs["slug"])
        slug = self.kwargs.get("slug")
        print(slug)
        obj = get_object_or_404(Query, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


class QueryLikeAPIToggle(APIView):
    authentication_classes = [
        SessionAuthentication,
    ]
    permission_clases = [
        IsAuthenticated,
    ]

    def get(self, request, slug=None):
        obj = get_object_or_404(Query, slug=slug)
        updated = False
        liked = False
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)

            updated = True
        data = {"updated": updated, "liked": liked}
        return Response(data)


"""
class AnswerLikeToggle(generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get('slug')
        print(slug)
        obj = get_object_or_404(Answer, slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


class AnswerLikeAPIToggle(APIView):
    authentication_classes = [SessionAuthentication, ]
    permission_clases = [IsAuthenticated, ]

    def get(self, request, slug=None, format=None):
        obj = get_object_or_404(Answer, slug=slug)
        updated = False
        liked = False
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)

            updated = True
        data = {
            'updated': updated,
            'liked': liked
        }
        return Response(data)
"""

forum/templates/forum/answer_detail.html
{% extends "notes/base.html" %}
{%load forumtags%}
{% block content %}
<p><a href="javascript:history.back()">Go Back</a></p>
<article class="media content-section shadow">
    <a href="{%url 'users:profilepage' object.user.profile.slug%}"><img class="rounded-circle article-img"
            src="{{ object.user.profile.image.url }}" /></a>
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">{{ object.created|date:"F d, Y" }}</small>
            <span class="badge badge-light badge-pill">{{object.category}}</span>

            {% if object.user == user %}
            <div>
                <small> <a class="badge badge-dark badge-pill"
                        href="{% url 'forum:query-update' answer.slug %}">Edit
                        ✏️️</a> <a class="badge badge-danger badge-pill"
                        href="{% url 'forum:query-delete' answer.slug %}">Delete</a></small>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        {{object.content|safe}}
    </div>
</article>
<span class="badge badge-dark badge-pill"> <a class="nav-item nav-link"
        href="{%url 'forum:comment-create' answer.query.slug answer.slug%}">Make a comment.</a></span>

{%for comment in object|comments%}
{%if comment.user == user%}
<div class="media-body shadow">
    <p>{{comment.content|safe}}</p>
    <small>
        <p> by <a href="{%url 'users:profilepage' comment.user.profile.slug %}">{{comment.user}}</a></p>
    </small>
    <small> <a class="badge badge-dark badge-pill"
            href="{% url 'forum:comment-update' answer.query.slug answer.slug comment.slug %}">Edit
            ✏️️</a> <a class="badge badge-danger badge-pill"
            href="{% url 'forum:comment-delete' answer.query.slug answer.slug comment.slug%}">Delete</a></small>
</div>
<hr>
{%else%}
<div class="media-body shadow">
    <p> {{comment.content|safe}}</p>
    <small>
        <p> by <a href="{%url 'users:profilepage' comment.user.profile.slug%}">{{comment.user}}</a></p>
    </small>
</div>
{%endif%}
{%endfor%}
{% endblock content %}

forum/templates/forum/answer_form.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section shadow">
    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        <small>We urge you to read the <a href="{%url 'forum:guidelines'%}">Guidelines</a> first.</small>
        {% csrf_token %}
        <fieldset class="form-group">

            <legend class="border-bottom mb-4">Answer</legend>
            {{form.media}}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Answer.</button>
        </div>
    </form>
</div>
{% endblock content %}

forum/templates/forum/comment_form.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section shadow">
    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        <small>We urge you to read the <a href="{%url 'forum:guidelines'%}">Guidelines</a> first.</small>
        {% csrf_token %}
        <fieldset class="form-group">

            <legend class="border-bottom mb-4">Comment</legend>
            {{form.media}}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Comment.</button>
        </div>
    </form>
</div>
{% endblock content %}

forum/templates/forum/query_detail.html
{% extends "notes/base.html" %}
{%load forumtags%}
{% block content %}
<p><a href="{%url 'forum:list'%}">Go Back</a></p>
<article class="media content-section shadow">
  <a href="{%url 'users:profilepage' object.user.profile.slug%}"><img class="rounded-circle article-img"
      src="{{ object.user.profile.image.url }}" /></a>
  <div class="media-body">
    <div class="article-metadata">
      <small class="text-muted">{{ object.created|date:"F d, Y" }}</small>
      <span class="badge badge-light badge-pill">{{object.category}}</span>

      {% if object.user == user %}
      <div>
        <small> <a class="badge badge-dark badge-pill" href="{% url 'forum:query-update' query.slug %}">Edit
            ✏️️</a> <a class="badge badge-danger badge-pill"
            href="{% url 'forum:query-delete' query.slug %}">Delete</a></small>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ object.title }}</h2>
    <button name="badge-info" id="like" class="badge badge-danger badge-pill" <a
      data-href="{%url 'forum:query-likes-api-toggle' object.slug%}" data-likes="{{object.likes.count}}"
      href="{%url 'forum:query-likes-toggle' object.slug%}" class="btn btn-info btn-sm">{{object.likes.count}} Likes
      </a></button>
    {% if request.user.id in object.likes_as_flat_user_id_list %}
    <span class="badge badge-dark badge-pill">Liked</span>
    {%endif%}
    <br><br>
    {{object.content|safe}}
  </div>
</article>
<span class="badge badge-dark badge-pill"> <a class="nav-item nav-link"
    href="{%url 'forum:answer-create' query.slug%}">Submit
    Answer</a></span>



{%for answer in object|answers%}
{%if answer.user == user%}
<div class="media-body shadow">
  <p>{{answer.content|safe}}</p>
  <small>
    <p> by <a href="{%url 'users:profilepage' answer.user.profile.slug %}">{{answer.user}}</a></p>
  </small>

  <small> <a class="badge badge-dark badge-pill" href="{% url 'forum:answer-update' query.slug answer.slug %}">Edit
      ✏️️</a> <a class="badge badge-danger badge-pill"
      href="{% url 'forum:answer-delete' query.slug answer.slug %}">Delete</a></small>

  <span class="badge badge-info badge-pill">Is this answer accepted?
    {%if answer.isaccepted is True%}Yes.{%else%}No.{%endif%}</span>

  <br><br>

  <small><a class="badge badge-danger badge-pill nav-link" style="font-size: small;"
      href="{%url 'forum:comment-create' query.slug answer.slug%}">Comment on this
      answer</a>
    <a class="badge badge-danger badge-pill nav-link" style="font-size: small;"
      href="{%url 'forum:answer-detail' query.slug answer.slug%}"> OR look at the comments.</a></small>
  <br><br>
  {%if answer.query.user == user%}
  {%if answer.isaccepted is True%}
  <small> <a style="font-size: small;" class="badge badge-danger badge-pill nav-link"
      href="{%url 'forum:accept' query.slug answer.slug%}">Unaccept this
      answer.</a></small>
  {%else%}
  <small> <a style="font-size: small;" class="badge badge-danger badge-pill nav-link"
      href="{%url 'forum:accept' query.slug answer.slug%}">Accept this
      answer.</a></small>
  {%endif%}
  {%endif%} 
</div>


{%else%}
<div class="media-body shadow">
  <p>{{answer.content|safe}}</p>
  <small>
    <p> by <a href="{%url 'users:profilepage' answer.user.profile.slug %}">{{answer.user}}</a></p>
  </small>
  <span class="badge badge-info badge-pill">Is this answer accepted?
    {%if answer.isaccepted is True%}Yes.{%else%}No.{%endif%}</span>
  <small><a class="badge badge-dark badge-pill nav-link" style="font-size: small;"
      href="{%url 'forum:comment-create' query.slug answer.slug%}">Comment on this
      answer.</a><small>
      <a class="badge badge-dark badge-pill nav-link" style="font-size: small;"
        href="{%url 'forum:answer-detail' query.slug answer.slug%}"> OR look at the comments.</a><small>
        <br><br>
        {%if answer.query.user == user%}
        <br><br>
        {%if answer.isaccepted is True%} <small> <a style="font-size: small;" class="badge badge-danger badge-pill"
            class="nav-link" href="{%url 'forum:accept' query.slug answer.slug%}">Unaccept this
            answer.</a></small>{%else%}
        <small> <a class="badge badge-danger badge-pill nav-link" style="font-size: small;"
            href="{%url 'forum:accept' query.slug answer.slug%}">Accept this
            answer.</a></small>

</div>
{%endif%}
{%endif%} 
{%endif%}
{%endfor%}
{% endblock content %}

forum/templates/forum/query_form.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section shadow">
    <p><a href="{%url 'forum:list'%}">Go Back</a></p>
    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Query</legend>
            <small>We urge you to read the <a href="{%url 'forum:guidelines'%}">Guidelines</a> first.</small>
            <br>
            {{form.media}}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Post it!</button>
        </div>
    </form>
</div>

{% endblock content %}

forum/templates/forum/query_list.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<h2>DomeCode's Forum.</h2>
<small>
    <p><a style="color: rgb(0, 238, 255); font-weight: bold;" href="{%url 'forum:guidelines'%}">Forum
            Guidelines</a></p>
</small>
<div class="col-sm-6">
    <div class="card-deck">
        <form class="form-inline" method="GET" autocomplete="off" action="/forum/">
            <div class="input-group">
                <input class="form-control mr-sm-2" type="search" name="q" class="form-control"
                    placeholder="content/keyword">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Search</button>
                </span>
            </div>
        </form>
    </div>
</div>
<br>
<small>Use the search option for searching specific keywords, categories that include <a style="color: aqua;">"About
        DomeCode"</a>, <a style="color: aqua;">"General Development"</a>,<a style="color: aqua;"> "Web Development"</a>
    and <a style="color: aqua;">"CS".</a></small>
<br><br>
<small class="text-muted">Your query has returned {{ paginator.count }}
    result{{ paginator.count|pluralize }}.</small><br><br>


<span class="badge badge-dark badge-pill"> <a style="color: aliceblue;" class="nav-item nav-link"
        href="{%url 'forum:query-create' %}">New Query</a></span>

<br>
<br>
<!--Improve Search with Incremental Search (AJAX and JQuery)-->
{% for queries in query %}
<article class="media content-section shadow" style="padding-bottom:15px ; padding-top: 15px;">
    <a href="{%url 'users:profilepage' queries.user.profile.slug%}"><img class="rounded-circle article-img"
            src="{{ queries.user.profile.image.url }}" /></a>
    <div class="media-body container-fluid">
        <div class="article-metadata">
            <small class="text-muted">Last modified on {{ queries.last_modified|date:"F d, Y" }}</small>
            <small class="text-muted">and created on {{ queries.created|date:"F d, Y" }}</small>
        </div>
        <span class="badge badge-light badge-pill">{{queries.category}}</span>
        <h4><a class="article-title" href="{% url 'forum:detail' queries.slug %}">{{ queries.title}}</a></h4>

        <button class="badge badge-info badge-pill">This query has {{queries.likes.count}} likes.
        </button>

    </div>
</article>
{% endfor %}
{% if page_obj.has_previous %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.previous_page_number }}">&laquo; Previous</a>

{% endif %}

{% for i in page_obj.paginator.page_range %}
{% if page_obj.number == i %}
<a class="page-link badge badge-dark badge-pill">Page {{ i }}</a>
{% else %}
<a class="page-link badge badge-dark badge-pill" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">
    {{ i }}</a>

{% endif %}
{% endfor %}

{% if page_obj.has_next %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>


<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last
    &raquo;</a>

{% endif %}

<br>

{% endblock content %}