coder/urls.py
from django.urls import path
from . import views
from .views import (
    CoderListViewPy,
    CoderListViewJava,
    CoderListViewGen,
    CoderDetailView,
    CoderCreateView,
    SubmissionListView,
)

app_name = "coder"

urlpatterns = [
    path("", views.coderhome, name="home"),
    path("python/", CoderListViewPy.as_view(), name="list-python"),
    path("java/", CoderListViewJava.as_view(), name="list-java"),
    path("general/", CoderListViewGen.as_view(), name="list-general"),
    path("question/<slug:slug>/", CoderDetailView.as_view(), name="detail"),
    path("submissions", SubmissionListView.as_view(), name="submissions"),
    path("<slug:qslug>/answer/", CoderCreateView.as_view(), name="submit"),
]

domecode/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from . import devsettings
from django.conf.urls.static import static
from decouple import config

admin.autodiscover()

urlpatterns = [
    path(config("ADMIN_URL"), admin.site.urls),
    path("oauth/", include("social_django.urls", namespace="social")),
    path(
        "profile/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("users.urls")),
    path("", include("notes.urls")),
    path("", include("forum.urls")),
    path("todo/", include("todo.urls")),
    path("tracks/", include("resources.urls")),
    path("practice/", include("coder.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("quiz/", include("quizzes.urls")),
    path("products/", include("creator.urls")),
    path("fusion/", include("fusion.urls")),
    # REST FRAMEWORK URLS
    path("api/todo/", include("todo.api.urls", "todo_api")),
    path("api/notes/", include("notes.api.urls", "notes_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

elif devsettings.DEBUG:
    urlpatterns += static(devsettings.MEDIA_URL,
                          document_root=devsettings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=devsettings.STATIC_ROOT)

todo/urls.py
from django.urls import path
from .views import TodoCreateView, TodoListView, TodoUpdateView, TodoDeleteView

app_name = "todo"

urlpatterns = [
    path("", TodoListView.as_view(), name="list"),
    path("<int:pk>/", TodoUpdateView.as_view(), name="update"),
    path("new/", TodoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="delete"),
]

coder/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from ckeditor.fields import RichTextField


class Question(models.Model):
    CATEGORY = [
        ("EASY", "Easy Difficulty"),
        ("MEDIUM", "Medium Difficulty"),
        ("HARD", "Hard Difficulty"),
        ("ADVANCED", "Advanced Difficulty"),
        ("IMPLEMENT", "Implementation"),
    ]
    TYPE = [
        ("JAVA", "Java"),
        ("PYTHON", "Python"),
        ("RUST", "Rust"),
        ("C++", "C++"),
        ("GO", "Go"),
        ("C", "C"),
        ("General", "General"),
    ]
    title = models.CharField(max_length=100)
    content = RichTextField()
    category = models.CharField(max_length=10,
                                choices=CATEGORY,
                                default="MEDIUM")
    typeof = models.CharField(max_length=10, choices=TYPE, default="PYTHON")
    solution = models.FileField(
        validators=[FileExtensionValidator(allowed_extensions=["txt"])],
        upload_to="media",
    )
    slug = models.SlugField(null=True, unique=True, max_length=256)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("coder:detail", kwargs={"slug": self.slug})


class Answer(models.Model):
    TYPE = [
        ("JAVA", "Java"),
        ("PYTHON", "Python"),
        ("RUST", "Rust"),
        ("C++", "C++"),
        ("GO", "Go"),
        ("C", "C"),
    ]

    user = models.ForeignKey(
        get_user_model(),
        null=True,
        on_delete=models.SET_NULL,
        related_name="submissionuser",
    )
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    iscorrect = models.BooleanField(default=False)
    language = models.CharField(max_length=10, choices=TYPE,
                                default="PYTHON")  # Stores the language ofc

    # Added the status field
    status = models.CharField(max_length=100, default="In Queue")
    response_from_judge = models.TextField(null=True)
    # Stores the response received from judge. Can be helpful in debugging later.

    result = models.FileField(
        validators=[
            FileExtensionValidator(allowed_extensions=[
                "txt", "py", "java", "cpp", "c++", "rs", "go", "c"
            ])
        ],
        upload_to="media",
        blank=True,
        null=True,
    )  # Allowed for other types of file extensions

coder/forms.py
from django import forms
from django.core.validators import FileExtensionValidator
from .models import Answer


class ResultForm(forms.ModelForm):
    result = forms.FileField(
        validators=[FileExtensionValidator(allowed_extensions=["txt"])])

    class Meta:
        model = Answer
        fields = ["result"]

coder/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
)
from django.db.models import Q
from domecode.mixins import PageTitleMixin

from django.conf import settings
from .models import Question, Answer
import requests
import json
import time


def coderhome(request):
    return render(request, "coder/coder_home.html", {"title": "Practice"})


class CoderListViewPy(PageTitleMixin, ListView):
    model = Question
    template_name = "coder/coder_list_python.html"
    context_object_name = "question"
    paginate_by = 15
    title = "Practice Python"

    def get_queryset(self, *args, **kwargs):
        object_list = super(CoderListViewPy,
                            self).get_queryset(*args, **kwargs)
        search = self.request.GET.get("q", None)
        if search:
            object_list = object_list.filter(
                Q(title__contains=search)
                | Q(content__contains=search)
                | Q(category__contains=search))
            return object_list.filter(typeof="PYTHON")
        else:
            return object_list.filter(typeof="PYTHON")


class CoderListViewGen(PageTitleMixin, ListView):
    model = Question
    template_name = "coder/coder_list_common.html"
    context_object_name = "question"
    paginate_by = 15
    title = "Practice"

    def get_queryset(self, *args, **kwargs):
        object_list = super(CoderListViewGen,
                            self).get_queryset(*args, **kwargs)
        search = self.request.GET.get("q", None)
        if search:
            object_list = object_list.filter(
                Q(title__contains=search)
                | Q(content__contains=search)
                | Q(category__contains=search))
            return object_list.filter(typeof="General")
        else:
            return object_list.filter(typeof="General")


class CoderListViewJava(PageTitleMixin, ListView):
    model = Question
    template_name = "coder/coder_list_java.html"
    context_object_name = "question"
    paginate_by = 15
    title = "Practice Java"

    def get_queryset(self, *args, **kwargs):
        object_list = super(CoderListViewJava,
                            self).get_queryset(*args, **kwargs)
        search = self.request.GET.get("q", None)
        if search:
            object_list = object_list.filter(
                Q(title__contains=search)
                | Q(content__contains=search)
                | Q(category__contains=search))
            return object_list.filter(typeof="JAVA")
        else:
            return object_list.filter(typeof="JAVA")


class SubmissionListView(PageTitleMixin, LoginRequiredMixin, ListView):
    model = Answer
    template_name = "coder/submissions.html"
    context_object_name = "submission"
    paginate_by = 25
    title = "Your Submissions"

    def get_queryset(self, *args, **kwargs):
        object_list = Answer.objects.filter(user=self.request.user)
        return object_list


class CoderDetailView(PageTitleMixin, DetailView):
    model = Question
    template_name = "coder/coder_detail.html"
    context_object_name = "question"
    title = "Practice"


class CoderCreateView(PageTitleMixin, LoginRequiredMixin, CreateView):
    model = Answer
    fields = ["result", "language"]
    context_object_name = "answer"
    template_name = "coder/coder_form.html"
    title = "Submit"

    def get_success_url(self):
        question = self.object.question
        return reverse("coder:detail", kwargs={"slug": question.slug})

    def form_valid(self, form):
        form.instance.user = self.request.user
        question = Question.objects.get(slug=self.kwargs["qslug"])

        form.instance.question = question
        expected_output = question.solution.read().decode(
            "utf-8")  # API won't compile this if you don't decode
        src_code = form.instance.result.read().decode("utf-8")

        # Judge API
        API_URL = "https://judge0.p.rapidapi.com/submissions/"
        querystring = {"base64_encoded": "false"}

        # Later change to wait = false
        headers_post = {
            "x-rapidapi-host": "judge0.p.rapidapi.com",
            "x-rapidapi-key": settings.JUDGE0_RAPID_API_KEY,
            "content-type": "application/json",
            "accept": "application/json",
        }

        LANGUAGE_CODES = {
            "PYTHON": 71,
            "JAVA": 62,
            "C++": 54,
            "RUST": 73,
            "GO": 60,
            "C": 50,
        }
        # Update above line whenever a new language is added

        data_post = {
            "source_code": src_code,
            "language_id": LANGUAGE_CODES[form.instance.language],
            "expected_output": expected_output,
        }
        data_post = json.dumps(data_post)
        response = requests.post(url=API_URL,
                                 data=data_post,
                                 headers=headers_post,
                                 params=querystring)
        token = json.loads(response.text)["token"]

        headers_get = {
            "x-rapidapi-host": "judge0.p.rapidapi.com",
            "x-rapidapi-key": settings.JUDGE0_RAPID_API_KEY,
        }
        status = "Processing"
        i = 0
        while status == "Processing" or status == "In Queue":
            response2 = requests.request("GET",
                                         API_URL + token,
                                         headers=headers_get,
                                         params=querystring)
            status = json.loads(response2.text)["status"]["description"]
            time.sleep(0.1)
            i = i + 1
            if (
                    i == 200
            ):  # Break if it takes more than 20 seconds (probably means api is down)
                status = "TLE"  # Setting the status = TLE
                break

        form.instance.status = status
        form.instance.response_from_judge = response2.text
        form.instance.iscorrect = form.instance.status == "Accepted"
        if (form.instance.iscorrect and
            (Answer.objects.filter(question=question).filter(
                iscorrect=True).filter(user=form.instance.user).count() == 0)):
            if form.instance.question.category == "EASY":
                form.instance.user.profile.domes += 10
            if form.instance.question.category == "MEDIUM":
                form.instance.user.profile.domes += 15
            if form.instance.question.category == "HARD":
                form.instance.user.profile.domes += 20
            if form.instance.question.category == "ADVANCED":
                form.instance.user.profile.domes += 30

        form.instance.user.profile.save()
        form.save()

        return super().form_valid(form)

coder/templates/coder/coder_detail.html
{% extends "notes/base.html" %}
{%load static%}
{%load viewans%}
{% block content %}
{%if user.is_authenticated%}
<p style="font-size: small;">Practice <a href="{%url 'coder:list-python'%}">Python</a> | <a
        href="{%url 'coder:list-java'%}">Java</a> | <a href="{%url 'coder:list-general'%}">General</a> |<a
        href="{%url 'coder:home'%}"> Look at what "Practice is all
        about".</a></p>
{%notsolved user question as result%}
{%if result%}
<h2 class="article-title" style="color: rgb(255, 255, 255);">{{ question.title }}</h2>
<span class="badge badge-light badge-pill">{{question.category}}</span>
<span class="badge badge-dark badge-pill">{{question.typeof}}</span>
{%else%}
<h2 class="article-title" style="color: rgb(255, 255, 255);">{{ question.title }} </h2>
<span class="badge badge-light badge-pill">{{question.category}}</span>
<span class="badge badge-dark badge-pill">{{question.typeof}}</span>
<small>Solved <img src="{%static 'coder/check.svg'%}" height="14" width="14"></a> </small>
{%endif%}
{%else%}
<h2 class="article-title" style="color: rgb(255, 255, 255);">{{ question.title }}</h2>
<span class="badge badge-light badge-pill">{{question.category}}</span>
<span class="badge badge-dark badge-pill">{{question.typeof}}</span>
{%endif%}

<div class="article-content shadow">
    {{question.content|safe}}
</div>



<br>

{%if user.is_authenticated%}
{%notsolved user question as result%}
{%if result%}
<span class="badge badge-dark badge-pill"> <a class="nav-item nav-link" href="{%url 'coder:submit' object.slug%}">Submit
        Answer</a></span>
<small><a href="{%url 'coder:submissions'%}">View your submissions and results here.</a></small>
{%else%}
<small><a href="{%url 'coder:submissions'%}">View your submissions and results here.</a></small>
{%endif%}
{%else%}
<span class="badge badge-dark badge-pill"> <a class="nav-item nav-link" href="{%url 'coder:submit' object.slug%}">Submit
        Answer</a></span>
{%endif%}
<hr>
<br>
<div class="article-content shadow">
    <p> <strong>NOTE</strong>

        These questions can be solved in either <i class="fab fa-java"> Java </i>, <i class="fab fa-python"> Python
        </i>,
        <i class="fab fa-rust"> Rust</i>, <i class="devicon-cplusplus-plain"> C++</i>, <i
            class="devicon-go-plain">Go</i> or <i class="devicon-c-plain"></i> !

        However, the language intended for these questions is mentioned along with the question on the top.
        You need to submit the solution file for the autograder to grade the submission.

        <strong>If you are submitting in Java, make sure that the class name is Main (with a capital M)</strong>
    </p>
</div>
<br>

{%if question.typeof == "PYTHON"%}
<p>Optional Python Editor for your use</p>
<iframe src="https://trinket.io/embed/python3/9d578a67e3" width="90%" height="400" frameborder="0" marginwidth="0"
    marginheight="0"></iframe>
{%elif question.typeof == "JAVA"%}
<p>Optional Java Editor for your use</p>
<iframe src="https://trinket.io/embed/java/d1fcaa7e44" width="90%" height="500" frameborder="0" marginwidth="0"
    marginheight="0" allowfullscreen></iframe>
{%elif question.typeof == "General"%}
<p>Optional Python Editor for your use</p>
<iframe src="https://trinket.io/embed/python3/9d578a67e3" width="90%" height="400" frameborder="0" marginwidth="0"
    marginheight="0"></iframe>
<p>Optional Java Editor for your use</p>
<iframe src="https://trinket.io/embed/java/d1fcaa7e44" width="90%" height="500" frameborder="0" marginwidth="0"
    marginheight="0" allowfullscreen></iframe>
{%endif%}
{% endblock content %}

coder/templates/coder/coder_form.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section shadow">
    <form method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Submit Answer</legend>
            {{ form.media }}
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Submit</button>
             
        </div>
    </form>
</div>
{% endblock content %}

coder/templates/coder/coder_home.html
{%extends "notes/base.html"%}
{%block content%}

<ul class="media-content shadow">
    <h1>Practice</h1>
    <br>
    <p style="font-size: small;">Practice <a href="{%url 'coder:list-python'%}">Python</a> | <a
            href="{%url 'coder:list-java'%}">Java</a> | <a href="{%url 'coder:list-general'%}">General</a> |<a
            href="{%url 'coder:home'%}"> Look at what "Practice is all
            about".</a></p>
    <hr>
    <br>
    <div class="media-content" style="font-size: 18px;">
        <p style="background: linear-gradient(to right, hsl(246, 100%, 73%), #fa44cd);
        -webkit-background-clip: text; background-clip:text;
        -webkit-text-fill-color: transparent;">
            Note that the problems are categorized with languages most appropriate to be used with them.
            You might solve them with any language of your choice and it's totally upto you but for your own sanity, you
            should try using the appropriate language.
            <br></p>
        <h4>Supported Languages</h4>
        <br>

        <li><img src="https://img.icons8.com/color/48/000000/python.png" /> Python</li>
        <li><img src="https://img.icons8.com/color/48/000000/golang.png" /> Go</li>
        <li><img src="https://img.icons8.com/color/48/000000/java-coffee-cup-logo.png" /> Java</li>
        <li><img src="https://img.icons8.com/color/48/000000/c-plus-plus-logo.png" /> C++</li>
        <li><img src="https://img.icons8.com/color/48/000000/c-programming.png" /> C</li>
        <li><i style="color:brown; font-size: 36px;" class="fab fa-rust"></i></i> Rust</li>
        <br>
        <p class="grad">
            Some problems on DomeCode's Practice module exist such that they might be challenging for some users. Hence,
            while
            solving problems researching for appropriate help with a concept is an important set of skill. While you'll
            be
            able
            to find the resources on DomeCode itself since with every release, the resources gathered increase both in
            quality
            and quantity, it is important to try this by yourself.
            <br><br>
            While a lot of competitive programming happening on-site disbars the use of Internet, in the real world of
            development, it's almost impossible to get around without looking up documentations, forums and the internet
            in
            general.
            <br><br>
            DomeCode's goal isn't to teach you competitive programming, it's primary objective is to advance your coding
            skills
            and practice them along with being able to use the features that would make the experience simply better for
            you
            without having to leave a single workspace.
            <br><br>
        </p>
    </div>
</ul>
{%endblock content%}

coder/templates/coder/coder_list_common.html
{% extends "notes/base.html" %}
{%load static%}
{%load viewans%}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-6">
    <div class="card-deck">
        <form class="form-inline" method="GET" autocomplete="off" action="/practice/general/">
            <div class="input-group">
                <input class="form-control mr-sm-2" type="search" name="q" class="form-control"
                    placeholder="content/keyword">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Search</button>
                </span>
            </div>
        </form>
    </div>
</div>

<!--Improve Search with Incremental Search (AJAX and JQuery)-->

<small class="text-muted"> Your query has returned {{ paginator.count }}
    result{{ paginator.count|pluralize }}.</small>

<br>
<p style="font-size: small;">Practice <a href="{%url 'coder:list-python'%}">Python</a> | <a href="{%url 'coder:list-java'%}">Java</a> | <a
    href="{%url 'coder:list-general'%}">General</a> |<a href="{%url 'coder:home'%}"> Look at what "Practice is all
    about".</a></p>

<h1>Practice </h1>

<br>

{% for object in question %}
<article class="media content-section shadow">
    <div class="media-body container-fluid">


        <span class="badge badge-light badge-pill">{{object.category}}</span>
        <span class="badge badge-dark badge-pill">{{object.typeof}}</span>
        <h3><a class="article-title" href="{%url 'coder:detail' object.slug%}">{{object.title }}</a></h3>

    </div>
</article>
{% endfor %}



{% if page_obj.has_previous %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.previous_page_number }}">&laquo; Previous</a>

{% endif %}

{% for i in page_obj.paginator.page_range %}
{% if page_obj.number == i %}
<a class="page-link badge badge-dark badge-pill">Page {{ i }}</a>
{% else %}
<a class="page-link badge badge-dark badge-pill" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">
    {{ i }}</a>

{% endif %}
{% endfor %}

{% if page_obj.has_next %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>


<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last
    &raquo;</a>

{% endif %}

<br>


{% endblock content %}

coder/templates/coder/coder_list_java.html
{% extends "notes/base.html" %}
{%load static%}
{%load viewans%}
{% load crispy_forms_tags %}
{% block content %}

<div class="col-sm-6">
    <div class="card-deck">
        <form class="form-inline" method="GET" autocomplete="off" action="/practice/java/">
            <div class="input-group">
                <input class="form-control mr-sm-2" type="search" name="q" class="form-control"
                    placeholder="content/keyword">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Search</button>
                </span>
            </div>
        </form>
    </div>
</div>



<!--Improve Search with Incremental Search (AJAX and JQuery)-->

<small class="text-muted"> Your query has returned {{ paginator.count }}
    result{{ paginator.count|pluralize }}.</small>

<br>

<p style="font-size: small;">Practice <a href="{%url 'coder:list-python'%}">Python</a> | <a href="{%url 'coder:list-java'%}">Java</a> | <a
    href="{%url 'coder:list-general'%}">General</a> |<a href="{%url 'coder:home'%}"> Look at what "Practice is all
    about".</a></p>

<h1>Practice </h1>

<br>

{% for object in question %}
<article class="media content-section shadow">
    <div class="media-body container-fluid">


        <span class="badge badge-light badge-pill">{{object.category}}</span>
        <span class="badge badge-dark badge-pill">{{object.typeof}}</span>
        <h3><a class="article-title" href="{%url 'coder:detail' object.slug%}">{{object.title }}</a></h3>

    </div>
</article>
{% endfor %}



{% if page_obj.has_previous %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.previous_page_number }}">&laquo; Previous</a>

{% endif %}

{% for i in page_obj.paginator.page_range %}
{% if page_obj.number == i %}
<a class="page-link badge badge-dark badge-pill">Page {{ i }}</a>
{% else %}
<a class="page-link badge badge-dark badge-pill" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">
    {{ i }}</a>

{% endif %}
{% endfor %}

{% if page_obj.has_next %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>


<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last
    &raquo;</a>

{% endif %}

<br>


{% endblock content %}

coder/templates/coder/coder_list_python.html
{% extends "notes/base.html" %}
{%load static%}
{%load viewans%}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-6">
    <div class="card-deck">
        <form class="form-inline" method="GET" autocomplete="off" action="/practice/python/">
            <div class="input-group">
                <input class="form-control mr-sm-2" type="search" name="q" class="form-control"
                    placeholder="content/keyword">
                <span class="input-group-btn">
                    <button class="btn btn-primary" type="submit">Search</button>
                </span>
            </div>
        </form>
    </div>
</div>


<!--Improve Search with Incremental Search (AJAX and JQuery)-->

<small class="text-muted"> Your query has returned {{ paginator.count }}
    result{{ paginator.count|pluralize }}.</small>

<br>
<p style="font-size: small;">Practice <a href="{%url 'coder:list-python'%}">Python</a> | <a href="{%url 'coder:list-java'%}">Java</a> | <a
    href="{%url 'coder:list-general'%}">General</a> |<a href="{%url 'coder:home'%}"> Look at what "Practice is all
    about".</a></p>

<h1>Practice </h1>

<br>

{% for object in question %}
<article class="media content-section shadow">
    <div class="media-body container-fluid">


        <span class="badge badge-light badge-pill">{{object.category}}</span>
        <span class="badge badge-dark badge-pill">{{object.typeof}}</span>
        <h3><a class="article-title" href="{%url 'coder:detail' object.slug%}">{{object.title }}</a></h3>

    </div>
</article>
{% endfor %}



{% if page_obj.has_previous %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.previous_page_number }}">&laquo; Previous</a>

{% endif %}

{% for i in page_obj.paginator.page_range %}
{% if page_obj.number == i %}
<a class="page-link badge badge-dark badge-pill">Page {{ i }}</a>
{% else %}
<a class="page-link badge badge-dark badge-pill" href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">
    {{ i }}</a>

{% endif %}
{% endfor %}

{% if page_obj.has_next %}

<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>


<a class="page-link badge badge-dark badge-pill"
    href="?{% if query %}q={{query}}&{% endif %}page={{ page_obj.paginator.num_pages }}">Last
    &raquo;</a>

{% endif %}

<br>


{% endblock content %}

coder/templates/coder/submissions.html
{% extends "notes/base.html" %}
{%load static%}
{% block content %}
<a href="javascript:history.back()">Go Back</a>
<h2>Your submissions</h2>
{%for submission in submission%}

{%if submission.iscorrect%}

{%if submission.question.category == "EASY" %}
- {{ submission.question.title }} ({{submission.question.typeof}} - {{submission.question.category}}) - <a
    href="{{submission.result.url}}">{{submission.result}} <img src="{%static 'coder/check.svg'%}" height="14"
        width="14"></a>(+10)
{%elif submission.question.category == "HARD" %}
- {{ submission.question.title }} ({{submission.question.typeof}} - {{submission.question.category}}) - <a
    href="{{submission.result.url}}">{{submission.result}} <img src="{%static 'coder/check.svg'%}" height="14"
        width="14"></a>(+20)
{%elif submission.question.category == "MEDIUM" %}
- {{ submission.question.title }} ({{submission.question.typeof}} - {{submission.question.category}}) - <a
    href="{{submission.result.url}}">{{submission.result}} <img src="{%static 'coder/check.svg'%}" height="14"
        width="14"></a>(+15)
{%elif submission.question.category == "ADVANCED" %}
- {{ submission.question.title }} ({{submission.question.typeof}} - {{submission.question.category}}) - <a
    href="{{submission.result.url}}">{{submission.result}} <img src="{%static 'coder/check.svg'%}" height="14"
        width="14"></a>(+30)
{%elif submission.question.category == "IMPLEMENT" %}
- {{ submission.question.title }} ({{submission.question.typeof}} - {{submission.question.category}}) - <a
    href="{{submission.result.url}}">{{submission.result}} <img src="{%static 'coder/check.svg'%}" height="14"
        width="14"></a>(No Points for Implmentation, knowledge dripped hard tho)
{%endif%}


<br>
{%else%}
- {{ submission.question.title }} ({{submission.question.typeof}} - {{submission.question.category}}) - <a
    href="{{submission.result.url}}">{{submission.result}} <img src="{%static 'coder/false.svg'%}" height="14"
        width="14"> {{submission.status}}</a>
<br>
{%endif%}
{%endfor%}

{% endblock content %}