coder/urls.py
from django.urls import path
from . import views
from .views import (
    CoderListViewPy,
    CoderListViewJava,
    CoderListViewGen,
    CoderDetailView,
    CoderCreateView,
    SubmissionListView,
)

app_name = "coder"

urlpatterns = [
    path("", views.coderhome, name="home"),
    path("python/", CoderListViewPy.as_view(), name="list-python"),
    path("java/", CoderListViewJava.as_view(), name="list-java"),
    path("general/", CoderListViewGen.as_view(), name="list-general"),
    path("question/<slug:slug>/", CoderDetailView.as_view(), name="detail"),
    path("submissions", SubmissionListView.as_view(), name="submissions"),
    path("<slug:qslug>/answer/", CoderCreateView.as_view(), name="submit"),
]

domecode/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from . import devsettings
from django.conf.urls.static import static
from decouple import config

admin.autodiscover()

urlpatterns = [
    path(config("ADMIN_URL"), admin.site.urls),
    path("oauth/", include("social_django.urls", namespace="social")),
    path(
        "profile/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("users.urls")),
    path("", include("notes.urls")),
    path("", include("forum.urls")),
    path("todo/", include("todo.urls")),
    path("tracks/", include("resources.urls")),
    path("practice/", include("coder.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("quiz/", include("quizzes.urls")),
    path("products/", include("creator.urls")),
    path("fusion/", include("fusion.urls")),
    # REST FRAMEWORK URLS
    path("api/todo/", include("todo.api.urls", "todo_api")),
    path("api/notes/", include("notes.api.urls", "notes_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

elif devsettings.DEBUG:
    urlpatterns += static(devsettings.MEDIA_URL,
                          document_root=devsettings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=devsettings.STATIC_ROOT)

forum/urls.py
from django.urls import path
from . import views
from .views import (
    QueryCreateView,
    QueryListView,
    QueryUpdateView,
    QueryDeleteView,
    QueryDetailView,
    QueryLikeAPIToggle,
    QueryLikeToggle,
    AnswerCreateView,
    AnswerDeleteView,
    AnswerUpdateView,
    AnswerDetailView,
    AcceptAnswerView,
    CommentCreateView,
    CommentDeleteView,
    CommentUpdateView,
)

app_name = "forum"

urlpatterns = [
    # forum url
    path("forum/", QueryListView.as_view(), name="list"),
    path("forum/guidelines", views.guidelines, name="guidelines"),
    # query urls
    path("forum/query/new/", QueryCreateView.as_view(), name="query-create"),
    path("forum/query/<slug:slug>/", QueryDetailView.as_view(), name="detail"),
    path(
        "forum/query/<slug:slug>/update/",
        QueryUpdateView.as_view(),
        name="query-update",
    ),
    path(
        "forum/query/<slug:slug>/delete/",
        QueryDeleteView.as_view(),
        name="query-delete",
    ),
    path(
        "forum/query/<slug:slug>/like/",
        QueryLikeToggle.as_view(),
        name="query-likes-toggle",
    ),
    path(
        "api/forum/query/<slug:slug>/like/",
        QueryLikeAPIToggle.as_view(),
        name="query-likes-api-toggle",
    ),
    # answer urls
    path(
        "forum/query/<slug:qslug>/answer/create/",
        AnswerCreateView.as_view(),
        name="answer-create",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:slug>/",
        AnswerDetailView.as_view(),
        name="answer-detail",
    ),
    path(
        "forum/query/<slug:qslug>/answer/update/<slug:slug>",
        AnswerUpdateView.as_view(),
        name="answer-update",
    ),
    path(
        "forum/query/<slug:qslug>/answer/delete/<slug:slug>/",
        AnswerDeleteView.as_view(),
        name="answer-delete",
    ),
    path(
        "forum/query/<slug:qslug>/answer/accept/<slug:slug>/",
        AcceptAnswerView.as_view(),
        name="accept",
    ),
    # commenturls
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/create/",
        CommentCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/update/<slug:slug>",
        CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/delete/<slug:slug>/",
        CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    # path('forum/query/<slug:qslug>/answer/like/',
    #     AnswerLikeToggle.as_view(), name='answer-likes-toggle'),
    #  path('api/forum/answer/<slug:slug>/like/',
    #      AnswerLikeAPIToggle.as_view(), name='answer-likes-api-toggle'),
]

fusion/urls.py
from django.urls import path
from .views import FusionHomeView, FusionDetailView

app_name = "fusion"

urlpatterns = [
    path("", FusionHomeView, name="fusion"),
    path("immerse/", FusionDetailView, name="fusion-detail"),
]

notes/api/urls.py
from django.urls import path
from notes.api import views

app_name = "notes"

urlpatterns = [
    path("", views.NotesList.as_view(), name="list"),
    path("<int:pk>/", views.NotesDetail.as_view(), name="detail"),
]

notes/urls.py
# todo - update the urls.py with private and public mode urls
from django.urls import path
from . import views
from .views import (
    NotesCreateView,
    NotesListView,
    NotesUpdateView,
    NotesDeleteView,
    NotesDetailView,
)

app_name = "notes"

urlpatterns = [
    path("", views.home, name="home"),
    path("notes/", NotesListView.as_view(), name="list"),
    path("notes/new/", NotesCreateView.as_view(), name="create"),
    path("notes/<slug:slug>/delete/", NotesDeleteView.as_view(),
         name="delete"),
    path("notes/<slug:slug>/", NotesDetailView.as_view(), name="detail"),
    path("notes/<slug:slug>/update/", NotesUpdateView.as_view(),
         name="update"),
    path("about/", views.about, name="about"),
    path("music/", views.music, name="music"),
    path("sponsor/", views.sponsor, name="sponsor"),
    path("privacypolicy/", views.privacy, name="privacy"),
    path("termsofservice/", views.tos, name="tos"),
]

todo/urls.py
from django.urls import path
from .views import TodoCreateView, TodoListView, TodoUpdateView, TodoDeleteView

app_name = "todo"

urlpatterns = [
    path("", TodoListView.as_view(), name="list"),
    path("<int:pk>/", TodoUpdateView.as_view(), name="update"),
    path("new/", TodoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.urls import path
from . import views
from users.views import AccountDetailView, Leaderboard

app_name = "users"

urlpatterns = [
    path("leaderboard/", Leaderboard.as_view(), name="leaderboard"),
    path("profile/register/", views.signup, name="register"),
    path("profile/edit/", views.profile, name="profile"),
    path("user/<slug:slug>/", AccountDetailView.as_view(), name="profilepage"),
]

notes/models.py
#!/usr/bin/env python3
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from ckeditor.fields import RichTextField


class Notes(models.Model):
    title = models.CharField(max_length=40)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = RichTextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    category = models.CharField(max_length=25, default="CS")
    slug = models.SlugField(null=True, unique=True, max_length=256)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("notes:detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        uniqueid = get_random_string(length=64)
        self.slug = slugify(uniqueid)
        super().save(*args, **kwargs)

notes/api/views.py
from notes.models import Notes
from notes.api.serializers import NotesSerializer
from rest_framework import generics
from rest_framework.permissions import IsAdminUser


class NotesList(generics.ListCreateAPIView):
    permission_classes = [IsAdminUser]
    queryset = Notes.objects.all()
    serializer_class = NotesSerializer


class NotesDetail(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = [IsAdminUser]
    queryset = Notes.objects.all()
    serializer_class = NotesSerializer

notes/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Notes
from django.db.models import Q
from domecode.mixins import PageTitleMixin


def home(request):
    return render(request, "notes/home.html", {"title": "Home"})


def about(request):
    return render(request, "notes/about.html", {"title": "About"})


def music(request):
    return render(request, "notes/musicpopup.html", {"title": "Music"})


def sponsor(request):
    return render(request, "notes/sponsor.html", {"title": "Sponsor"})


def privacy(request):
    return render(request, "notes/privacy.html", {"title": "Privacy Policy"})


def tos(request):
    return render(request, "notes/termsofservice.html",
                  {"title": "Terms of Service"})


class NotesListView(LoginRequiredMixin, PageTitleMixin, ListView):
    model = Notes
    context_object_name = "notes"
    title = "Your Notes"
    paginate_by = 15

    def get_queryset(self, *args, **kwargs):
        object_list = super(NotesListView, self).get_queryset(*args, **kwargs)
        search = self.request.GET.get("q", None)

        if search:
            object_list = object_list.filter(
                Q(title__contains=search, user=self.request.user)
                | Q(content__contains=search, user=self.request.user)
                | Q(category__contains=search, user=self.request.user)
            ).order_by("-last_modified")
            return object_list
        else:
            object_list = Notes.objects.filter(
                user=self.request.user).order_by("-last_modified")
            return object_list


class NotesUpdateView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                      UpdateView):
    model = Notes
    success_url = reverse_lazy("notes:list")
    title = "Update Note"
    fields = ["title", "content", "category"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        notes = self.get_object()
        if self.request.user == notes.user:
            return True


class NotesDetailView(PageTitleMixin, LoginRequiredMixin, UserPassesTestMixin,
                      DetailView):
    model = Notes
    title = "Notes"

    def test_func(self):
        notes = self.get_object()
        if self.request.user == notes.user:
            return True


class NotesDeleteView(LoginRequiredMixin, UserPassesTestMixin, PageTitleMixin,
                      DeleteView):
    model = Notes
    success_url = reverse_lazy("notes:list")
    title = "Delete Note"

    def test_func(self):
        notes = self.get_object()
        if self.request.user == notes.user:
            return True


class NotesCreateView(LoginRequiredMixin, PageTitleMixin, CreateView):
    model = Notes
    fields = ["title", "content", "category"]
    title = "Create Note"
    success_url = reverse_lazy("notes:list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

notes/templates/notes/home.html
{%extends "notes/base.html"%}
{% block content%}
<div class="fade-in">
	<div class="d-flex justify-content-center ">
		<a style="font-family:'Flavors' ;font-weight: bolder;  font-size:20vw ;  background: linear-gradient(to right, #f12711, #f5af19);
					-webkit-background-clip: text; background-clip:text;
	-webkit-text-fill-color: transparent;">DomeCode</a>

	</div>
	<br>
	<div class="d-flex justify-content-center" style="font-family: Mulish; font-size: 38px;">
		<p>Get more. With less hassle. Free & Open Source.</p>
	</div>
	<br>
	<div class="d-flex justify-content-center">
		<p style="font-family: Mulish; font-size: 28px; font-weight: lighter; background: linear-gradient(to right, #ffc340, #ff2c15);
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">Learn. Practice. Discuss. Have the musical element. All in one place. And
			more.</p>
	</div>
	{%if not user.is_authenticated%}
	<div class="d-flex justify-content-center" style="font-family: Mulish; font-size: 21px; font-weight: lighter; ">
		<p><a style="background: linear-gradient(to right, #ff2c15, #ffc340);
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">Let DomeCode be the partner in your coding journey.</a>
			<br>
			<a href="{%url 'users:register'%}" style="font-weight: bold; color: aliceblue;">Sign up</a> or <a
				href="{%url 'login'%}" style="font-weight: bold; color: aliceblue;">Login</a>
			using Github
			<i class="fab fa-github"></i> or Google <i style="color: rgb(255, 0, 0);" class="fab fa-google"></i> today.
		</p>
	</div>
	{%endif%}
	<hr>
	<div class=" d-flex justify-content-center">
		<p style="font-family: Mulish; font-size: 20px; font-weight: bold;background: linear-gradient(to right, #6085ff, hsl(211, 100%, 82%));
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">DomeCode is an open source platform to help you advance your coding journey
			with pre-existing resources to learn programming concepts ( in Python as of now ), take notes, plan tasks,
			practice coding problems in 6 different languages including,

			<img src="https://img.icons8.com/color/96/000000/python.png" /> Python,
			<img src="https://img.icons8.com/color/96/000000/golang.png" /> Go,
			<img src="https://img.icons8.com/color/96/000000/java-coffee-cup-logo.png" /> Java,
			<img src="https://img.icons8.com/color/96/000000/c-plus-plus-logo.png" /> C++,
			<img src="https://img.icons8.com/color/96/000000/c-programming.png" /> C or Rust.

			<br>

			You can also discuss interesting stuff on the forum, meet
			other
			developers and most all even get to listen to music conveniently without ever leaving this open source
			platform
			to
			navigate to paid platforms.
		</p>
	</div>
	<hr>
	<div class=" d-flex justify-content-center">
		<p style="font-family: Mulish; font-size: 10vw; font-weight: bold; background: linear-gradient(to right,  hsl(246, 100%, 85%), #fa44cd);
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">Features</p>
	</div>
	<br>
	<br>

	<div class=" d-flex justify-content-center">
		<p style="font-family: Mulish; font-size: 36px; font-weight: bold; background: linear-gradient(to right, #6085ff, hsl(211, 100%, 82%));
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">Growth Tools</p>
	</div>
	<br>
	<div class="row container-fluid shadow">
		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/lesson.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">TRACKS</h5>
					<p class="card-text">
						Learn to code in Python and Java with a curated list of resources. There's always more content
						being compiled and added to DomeCode with each release.
					</p>
					<a href="{%url 'resources:home'%}" class="btn btn-primary">Go check out Tracks</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/coding.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color: antiquewhite;">PRACTICE</h5>
					<p class="card-text">
						The Practice module has sorted problems for you to implement your coding skills.
					</p>
					<a href="{%url 'coder:home'%}" class="btn btn-primary">Practice now?</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/quiz.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">QUIZZES</h5>
					<p class="card-text">
						You can try out the quizzes on the concepts from Tracks and test your understanding.
					</p>
					<a href="{%url 'quizzes:home'%}" class="btn btn-primary">Go to Quizzes</a>
				</div>
			</div>
		</div>
	</div>
	<br>
	<div class=" d-flex justify-content-center"> <a style="font-family: Mulish; font-size: 36px; font-weight: bold; background: linear-gradient(to right, #6085ff, hsl(211, 100%, 82%));
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">Additional Tools</a>
	</div>
	<br>
	<div class="row container-fluid shadow">
		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/badge.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">LEADERBOARD</h5>
					<p class="card-text">
						Earn points through <strong>Quizzes</strong> and <strong>Practice problems</strong> to end up in
						the Top 100!
					</p>
					<a href="{%url 'users:leaderboard'%}" class="btn btn-primary">Leaderboard</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/music.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color: antiquewhite;">MUSIC</h5>
					<p class="card-text">
						Have a little musical element to keep focused right from here. It's lo-fi non lyrical music.
					</p>
					<a href="{%url 'notes:music'%}" onClick="return popup(this, 'notes')" class="btn btn-primary">Play
						Music</a>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/forum1.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">FORUM</h5>
					<p class="card-text">
						These are Geddit Forums. The latest feature of Geddit. Hop on it!
					</p>
					<a href="{%url 'forum:list'%}" class="btn btn-primary">Go check out Forum</a>
				</div>
			</div>
		</div>
	</div>
	<br>
	<div class=" d-flex justify-content-center">
		<p style="font-family: Mulish; font-size: 36px; font-weight: bold; background: linear-gradient(to right, #6085ff, hsl(211, 100%, 82%));
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;">Planning Tools</p>
	</div>
	<br>
	<div class="row container-fluid shadow">

		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/notes.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">NOTES</h5>
					<p class="card-text">
						Your notes lie here. You can label your notes as well. Your plans on
						learning code, music or maybe something else?
					</p>
					<a href="{%url 'notes:list'%}" class="btn btn-primary">Your Notes</a>
				</div>
			</div>
		</div>

		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/fire.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">CREATOR</h5>
					<p class="card-text">
						Creator is a shareable listing of your product that encapsulates all the other listings of your
						product.
						It's tailored for developers who like building stuff.
					</p>
					<a href="{%url 'todo:list'%}" class="btn btn-primary">Create</a>
				</div>
			</div>
		</div>


		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/tasks.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">TASKS</h5>
					<p class="card-text">
						You can plan out your tasks from right within DomeCode. Pretty sick, right?
					</p>
					<a href="{%url 'todo:list'%}" class="btn btn-primary">Your Tasks</a>
				</div>
			</div>
		</div>

	</div>
</div>
<br>
<p class="d-flex justify-content-center">The whole point was to have an integrated platform for all your needs and now
	it's being as open-source.<strong></p>
<div class=" d-flex justify-content-center" style="font-family: Mulish; font-size: 28px; font-weight: bold;">
	<br>
	<p style="font-size: larger; background: linear-gradient(to right, #ffc340, #ff2c15);
	-webkit-background-clip: text; background-clip:text;
	-webkit-text-fill-color: transparent;"><a style="font-weight:lighter ;">Consider</a> <a style="font-weight: bolder;"
			href="{%url 'notes:sponsor'%}">sponsoring us.</a></p>
</div>
<hr>
<br>
{%if not user.is_authenticated%}
<div class="fade-in d-flex justify-content-center" style="font-family: Mulish; font-size: 34px; font-weight: bold;">
	<p><a style="font-weight: bolder;  background: linear-gradient(to right, hsl(246, 100%, 73%), #fa44cd);
		-webkit-background-clip: text; background-clip:text;
		-webkit-text-fill-color: transparent;" href="{%url 'users:register'%}">Get started now!</a></p>
</div>
{%endif%}
</div>

{%endblock content%}



<!--		<div class="col-md-4">
			<div class="card-deck">
				<div class="card-body">
					<img class="card-img-top" src="/static/images/notes.png" alt="Card image cap">
					<br><br><br>
					<h5 class="card-title" style="color:antiquewhite;">NOTES</h5>
					<p class="card-text">
						Your notes lie here. You can label your notes as well. Your plans on
						learning code, music or maybe something else?
					</p>
					<a href="{%url 'notes:list'%}" class="btn btn-primary">Go check your notes</a>
				</div>
			</div>
		</div>
-->

notes/templates/notes/notes_confirm_delete.html
{% extends "notes/base.html" %}
{% block content %}
    <div class="content-section shadow">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Note</legend>
                <h2>Are you sure you want to delete the note? "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'notes:detail' object.slug  %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

notes/templates/notes/notes_detail.html
{% extends "notes/base.html" %}
{% block content %}
<article class="media content-section shadow">
  <img class="rounded-circle article-img" src="{{ object.user.profile.image.url }}" />
  <div class="media-body">
    <div class="article-metadata">
      <small class="text-muted">{{ object.created|date:"F d, Y" }}</small>
      <span class="badge badge-info badge-pill">{{object.category}}</span>

      {% if object.user == user %}
      <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'notes:update' object.slug %}">Update</a>
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'notes:delete' object.slug %}">Delete</a>
      </div>
      {% endif %}
    </div>
    <h2 class="article-title">{{ object.title }}</h2>
    {{object.content|safe}}
  </div>
  <p><a href="{%url 'notes:list'%}">Go Back</a></p>
</article>
{% endblock content %}