coder/urls.py
from django.urls import path
from . import views
from .views import (
    CoderListViewPy,
    CoderListViewJava,
    CoderListViewGen,
    CoderDetailView,
    CoderCreateView,
    SubmissionListView,
)

app_name = "coder"

urlpatterns = [
    path("", views.coderhome, name="home"),
    path("python/", CoderListViewPy.as_view(), name="list-python"),
    path("java/", CoderListViewJava.as_view(), name="list-java"),
    path("general/", CoderListViewGen.as_view(), name="list-general"),
    path("question/<slug:slug>/", CoderDetailView.as_view(), name="detail"),
    path("submissions", SubmissionListView.as_view(), name="submissions"),
    path("<slug:qslug>/answer/", CoderCreateView.as_view(), name="submit"),
]

domecode/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from . import devsettings
from django.conf.urls.static import static
from decouple import config

admin.autodiscover()

urlpatterns = [
    path(config("ADMIN_URL"), admin.site.urls),
    path("oauth/", include("social_django.urls", namespace="social")),
    path(
        "profile/login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include("users.urls")),
    path("", include("notes.urls")),
    path("", include("forum.urls")),
    path("todo/", include("todo.urls")),
    path("tracks/", include("resources.urls")),
    path("practice/", include("coder.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("quiz/", include("quizzes.urls")),
    path("products/", include("creator.urls")),
    path("fusion/", include("fusion.urls")),
    # REST FRAMEWORK URLS
    path("api/todo/", include("todo.api.urls", "todo_api")),
    path("api/notes/", include("notes.api.urls", "notes_api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

elif devsettings.DEBUG:
    urlpatterns += static(devsettings.MEDIA_URL,
                          document_root=devsettings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=devsettings.STATIC_ROOT)

forum/urls.py
from django.urls import path
from . import views
from .views import (
    QueryCreateView,
    QueryListView,
    QueryUpdateView,
    QueryDeleteView,
    QueryDetailView,
    QueryLikeAPIToggle,
    QueryLikeToggle,
    AnswerCreateView,
    AnswerDeleteView,
    AnswerUpdateView,
    AnswerDetailView,
    AcceptAnswerView,
    CommentCreateView,
    CommentDeleteView,
    CommentUpdateView,
)

app_name = "forum"

urlpatterns = [
    # forum url
    path("forum/", QueryListView.as_view(), name="list"),
    path("forum/guidelines", views.guidelines, name="guidelines"),
    # query urls
    path("forum/query/new/", QueryCreateView.as_view(), name="query-create"),
    path("forum/query/<slug:slug>/", QueryDetailView.as_view(), name="detail"),
    path(
        "forum/query/<slug:slug>/update/",
        QueryUpdateView.as_view(),
        name="query-update",
    ),
    path(
        "forum/query/<slug:slug>/delete/",
        QueryDeleteView.as_view(),
        name="query-delete",
    ),
    path(
        "forum/query/<slug:slug>/like/",
        QueryLikeToggle.as_view(),
        name="query-likes-toggle",
    ),
    path(
        "api/forum/query/<slug:slug>/like/",
        QueryLikeAPIToggle.as_view(),
        name="query-likes-api-toggle",
    ),
    # answer urls
    path(
        "forum/query/<slug:qslug>/answer/create/",
        AnswerCreateView.as_view(),
        name="answer-create",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:slug>/",
        AnswerDetailView.as_view(),
        name="answer-detail",
    ),
    path(
        "forum/query/<slug:qslug>/answer/update/<slug:slug>",
        AnswerUpdateView.as_view(),
        name="answer-update",
    ),
    path(
        "forum/query/<slug:qslug>/answer/delete/<slug:slug>/",
        AnswerDeleteView.as_view(),
        name="answer-delete",
    ),
    path(
        "forum/query/<slug:qslug>/answer/accept/<slug:slug>/",
        AcceptAnswerView.as_view(),
        name="accept",
    ),
    # commenturls
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/create/",
        CommentCreateView.as_view(),
        name="comment-create",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/update/<slug:slug>",
        CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "forum/query/<slug:qslug>/answer/<slug:aslug>/comment/delete/<slug:slug>/",
        CommentDeleteView.as_view(),
        name="comment-delete",
    ),
    # path('forum/query/<slug:qslug>/answer/like/',
    #     AnswerLikeToggle.as_view(), name='answer-likes-toggle'),
    #  path('api/forum/answer/<slug:slug>/like/',
    #      AnswerLikeAPIToggle.as_view(), name='answer-likes-api-toggle'),
]

notes/urls.py
# todo - update the urls.py with private and public mode urls
from django.urls import path
from . import views
from .views import (
    NotesCreateView,
    NotesListView,
    NotesUpdateView,
    NotesDeleteView,
    NotesDetailView,
)

app_name = "notes"

urlpatterns = [
    path("", views.home, name="home"),
    path("notes/", NotesListView.as_view(), name="list"),
    path("notes/new/", NotesCreateView.as_view(), name="create"),
    path("notes/<slug:slug>/delete/", NotesDeleteView.as_view(),
         name="delete"),
    path("notes/<slug:slug>/", NotesDetailView.as_view(), name="detail"),
    path("notes/<slug:slug>/update/", NotesUpdateView.as_view(),
         name="update"),
    path("about/", views.about, name="about"),
    path("music/", views.music, name="music"),
    path("sponsor/", views.sponsor, name="sponsor"),
    path("privacypolicy/", views.privacy, name="privacy"),
    path("termsofservice/", views.tos, name="tos"),
]

quizzes/urls.py
from django.urls import path
from .views import AnswerCreateView, QuesDetailView, QuizDetailView, QuizHomeView

app_name = "quizzes"

urlpatterns = [
    path("", QuizHomeView.as_view(), name="home"),
    path("python/<slug:slug>", QuizDetailView.as_view(), name="detail-python"),
    path("question/<slug:slug>", QuesDetailView.as_view(), name="detail"),
    path("<slug:qslug>/answer/", AnswerCreateView.as_view(), name="submit"),
]

todo/urls.py
from django.urls import path
from .views import TodoCreateView, TodoListView, TodoUpdateView, TodoDeleteView

app_name = "todo"

urlpatterns = [
    path("", TodoListView.as_view(), name="list"),
    path("<int:pk>/", TodoUpdateView.as_view(), name="update"),
    path("new/", TodoCreateView.as_view(), name="create"),
    path("<int:pk>/delete/", TodoDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.urls import path
from . import views
from users.views import AccountDetailView, Leaderboard

app_name = "users"

urlpatterns = [
    path("leaderboard/", Leaderboard.as_view(), name="leaderboard"),
    path("profile/register/", views.signup, name="register"),
    path("profile/edit/", views.profile, name="profile"),
    path("user/<slug:slug>/", AccountDetailView.as_view(), name="profilepage"),
]

users/models.py
from django.db import models
from django.core.validators import validate_image_file_extension
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils.text import slugify


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(
        null=True,
        blank=True,
        default="default.jpg",
        upload_to="profile_pics/",
        validators=[validate_image_file_extension],
    )
    about = models.CharField(null=True, blank=True, max_length=200)
    githubusername = models.CharField(null=True, blank=True, max_length=80)
    domes = models.IntegerField(default=0)
    slug = models.SlugField(null=True, unique=True, max_length=256)

    def __str__(self):
        return f"{self.user.username} Profile"

    def get_absolute_url(self):
        return reverse_lazy("users:profilepage", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        username = self.user.username
        self.slug = slugify(username)
        super().save(*args, **kwargs)


#      img = Image.open(self.image.path)

#        if img.height > 500 and img.width > 500:
#           img = img.resize((500, 500), Image.ANTIALIAS)
#          img.save(self.image.path, quality=90)

#        if img.height > 500 and img.width < 500:
#           img = img.resize((img.width, img.width), Image.ANTIALIAS)
#          img.save(self.image.path, quality=90)

#        if img.height < 500 and img.width > 500:
#           img = img.resize((img.height, img.height), Image.ANTIALIAS)
#          img.save(self.image.path, quality=90)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    first_name = forms.CharField(max_length=100, required=True)

    class Meta:
        model = User
        fields = ["username", "email", "first_name"]


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ["image", "about", "githubusername"]
        labels = {
            "image": "Profile Pic (500x500 is preferred resolution)",
            "about": "About you (max 200 words)",
            "githubusername":
            "Github Username ( if you wanna let others see it )",
        }
        widgets = {"image": forms.FileInput()}

users/views.py
from users.models import Profile
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfileUpdateForm
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from domecode.mixins import PageTitleMixin


def signup(request):
    return render(request, "users/register.html", {"title": "Register"})


class Leaderboard(PageTitleMixin, ListView):
    model = Profile
    template_name = "users/leaderboard.html"
    title = "Leaderboard"
    context_object_name = "profile"

    def get_queryset(self, *args, **kwargs):
        object_list = super(Leaderboard, self).get_queryset(*args, **kwargs)
        return object_list.order_by("-domes")[:100]


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "Your profile has been updated!")
            return redirect("users:profile")
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {"u_form": u_form, "p_form": p_form}
    return render(request, "users/profile.html", context)


class AccountDetailView(PageTitleMixin, LoginRequiredMixin, DetailView):
    model = Profile
    title = "User Profile"
    template_name = "users/profilepage.html"

users/templates/users/leaderboard.html
{%extends "notes/base.html"%}
{%block content%}
<h1><a style="font-family:'Flavors' ;font-weight: bolder;  font-size:40px ;  background: linear-gradient(to right, #f12711, #f5af19);
    -webkit-background-clip: text; background-clip:text;
    -webkit-text-fill-color: transparent;">DomeCode </a>Leaderboard - <a
        style="color:rgb(255, 255, 255); font-family:'Raleway';">Top 100</a></h1>
<small>This is DomeCode Leaderboard's Top 100. You can earn points by attempting question in the Quiz module and/or
    attempting problems in
    the Practice Module. Have fun!</small>
<hr>
<ol>
    {%for profile in profile%}
    <li><a style="color: beige;" href="{% url 'users:profilepage' profile.slug%}">{{profile.user.username}}</a> <a> - </a> <a
            style=" color: rgb(235, 192, 99); background-color: rgb(41, 41, 41);"> {{profile.domes}} Domes</a></li>
    <hr>
    {%endfor%}
</ol>

{%endblock content%}

users/templates/users/login.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section shadow">
    <p>DomeCode offers authentication with well-known services like Github <i style="color: rgb(255, 255, 255);"
            class="fab fa-github"></i>, Google <i style="color: rgb(255, 0, 0);" class="fab fa-google"></i> and the new
        privacy-focused AppleID <i style="color: rgb(255, 255, 255);" class="fab fa-apple"></i> is coming soon to
        DomeCode as well.</p>
    <hr>
    <span class="badge badge-dark badge-pill">
        {%if request.GET.next %}
        <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
            href="{% url 'social:begin' 'github' %}?next={{ request.GET.next }}">Login with Github <i
                class="fab fa-github"></i></a>
        {%else%}
        <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
            href="{% url 'social:begin' 'github' %}?next={{ request.GET.next }}/">Login with Github <i
                class="fab fa-github"></i></a>
        {%endif%}
    </span>
    <br><br>
    <span class="badge badge-danger badge-pill">
        {%if request.GET.next %}
        <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
            href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.GET.next }}">Login
            with Google <i class="fab fa-google"></i></a></span>
    {%else%}
    <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
        href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.GET.next }}/">Login
        with Google <i class="fab fa-google"></i></a></span>
    {%endif%}
    <hr>

    <small style="color: rgb(97, 97, 255);"><a href="{%url 'users:register'%}">Register</a>, maybe?</small>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section shadow">
  <div class="media"><img class="rounded-circle account-img" src="{{user.profile.image.url }}">
    <div class="media-body">
      <a class="badge badge-light badge-pill"
          href="{%url 'users:profilepage' user.profile.slug%}">{{user.username}}</a>
      <h3 class="account-heading">{{ user.first_name }}</h3>
    </div></div>
  <form method="POST" enctype="multipart/form-data" id="profile_ajax">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Profile Info</legend>
      {{ u_form| crispy}}
      {{ p_form| crispy}}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Update Your Profile</button>
    </div>
  </form>
</div>
{% endblock content %}

users/templates/users/profilepage.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section shadow">

  <div class="media">
    <img class="rounded-circle account-img" src="{{profile.image.url }}">
      <a class="badge badge-light badge-pill"
          href="{%url 'users:profilepage' profile.slug%}">{{profile.user.username}}</a>
        </div>
        <div class="media-body">
      {%if request.user.username == profile.user.username%}
      <small class="text-muted">
        <p>Psst...users outside DomeCode can't see your profile. This is what makes DomeCode more privacy-focused.</p>
      </small>

      <a class="btn badge btn-sm badge-pill badge-dark " href="{% url 'users:profile' %}">Edit ✏️️</a>
      {%endif%}
      <h3 class="account-heading">{{ profile.user.first_name }}</h3>
      <p class="text-secondary">{{ profile.user.email }}</p>
      {%if profile.githubusername is not None%}
      <p class="text-secondary" style="background-color: rgb(26, 26, 26); font-size: larger;"><a
          style=" color: rgb(235,192,99);" href="https://github.com/{{profile.githubusername}}" target=_new> Github <i
            style="color: rgb(255, 255, 255); font-size: larger;" class="fab fa-github"></i></a></p>
      {%endif%}
      <p style="font-size: larger; color: rgb(235, 192, 99); background-color: rgb(26, 26, 26);">Domes:
        {{profile.domes}}</p>
      <h3>About</h3>
      {%if profile.about is not None%}
      <p>{{profile.about}}</p>
      {%else%}
      <small class='text-muted'>
        <p>This person doesn't have their About filled up.</p>
      </small>

      {%endif%}
    </div>

      <br>
      {%if request.user.username == profile.user.username%}
      <div class=" card-deck">
        <div class="row">
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'notes:list'%}" class="btn btn-primary">Your Notes</a>
          </div>
          <br><br><br>
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'todo:list'%}" class="btn btn-primary">Your Tasks</a>
          </div>
          <br><br><br>
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'forum:list'%}" class="btn btn-primary">Visit Forum</a>
          </div>
          <br><br><br>
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'users:leaderboard'%}" class="btn btn-primary">Leaderboard</a>
          </div>
        </div>
        <hr>
      </div>
      <br>
      <div class="card-deck">
        <div class="row">
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'coder:home'%}" class="btn btn-primary">Learn </a>
          </div>
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'coder:home'%}" class="btn btn-primary">Practice</a>
          </div>
          <div class="col-xl col-lg-2" style="padding-bottom: 20px;">
            <a href="{%url 'quizzes:home'%}" class="btn btn-primary">Trivia</a>
          </div>
        </div>
      </div>
      <br>
      <div class="accordion" id="accordionExample">
        <div class="container-fluid">
          <div class="card-header" id="headingOne">
            <h2 class="mb-0">
              <span class="btn btn-link badge nav-link" type="button" data-toggle="collapse" data-target="#collapseOne"
                aria-expanded="true" aria-controls="collapseOne">
                Rewards
              </span>
            </h2>
          </div>
          <div id="collapseOne" class="collapse show " aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
              <div class="media content-section shadow">
                <ol> 
                  <li>GitKraken - Pro using this <a href="https://www.gitkraken.com/invite/q4P3SkPP">link</a> to have a
                    chance at winning a $100 Amazon Gift Card. For Free</li>
                  <p>More rewards coming soon!</p>
                </ol>
              </div>
            </div>
          </div>
        </div>
        <hr>
      </div>
      <br>
      <div class="card-deck">
        <div class="row">
          <div class="col-sm">
            <a href="{%url 'logout'%}" class="btn btn-danger btn-sm">Logout</a>
          </div>
        </div>
      </div>
      {%endif%}

</div>


{% endblock content %}

users/templates/users/register.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="content-section shadow">
        <p>DomeCode offers authentication with well-known services like Github <i style="color: rgb(255, 255, 255);"
                        class="fab fa-github"></i>, Google <i style="color: rgb(255, 0, 0);" class="fab fa-google"></i>
                and the new
                privacy-focused AppleID <i style="color: rgb(255, 255, 255);" class="fab fa-apple"></i> is coming soon
                to
                DomeCode as well.</p>
        <hr>
        <span class="badge badge-dark badge-pill">
                {%if request.GET.next%}

                <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
                        href="{% url 'social:begin' 'github' %}?next={{ request.GET.next }}">Sign up with
                        Github <i class="fab fa-github"></i></a></span>

        {%else%}

        <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
                href="{% url 'social:begin' 'github' %}?next={{ request.GET.next }}/">Sign up with
                Github <i class="fab fa-github"></i></a></span>
        {%endif%}

        <br><br>
        <span class="badge badge-danger badge-pill">
                {%if request.GET.next%}
                <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
                        href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.GET.next }}">Sign
                        up with Google <i class="fab fa-google"></i></a>


                {%else%}
                <a style="color:rgb(255, 255, 255);font-size:18px ;" class="nav-item nav-link"
                        href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.GET.next }}/">Sign
                        up with Google <i class="fab fa-google"></i></a>
        </span>
        {%endif%}

        <hr>
        <small style="color: rgb(124, 124, 255);">Already a DomeCode user? <a href="{%url 'login'%}">Signin</a></small>

</div>
{% endblock content %}